export interface MapUser {
  id: string;
  username: string;
  avatar: string;
  lat: number;
  lng: number;
  status: "online" | "idle" | "offline";
  bio: string;
  lastSeen: string;
  distance: string;
}

export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  category: string;
  shop: "designer" | "intimates" | "athletics";
  description: string;
  rating: number;
  reviews: number;
  badge?: string;
  colors?: string[];
  sizes?: string[];
}

export interface MerchantStats {
  totalRevenue: number;
  totalOrders: number;
  totalProducts: number;
  conversionRate: number;
  avgOrderValue: number;
  monthlyGrowth: number;
}

export const MAP_USERS: MapUser[] = [
  {
    id: "1",
    username: "alex_m",
    avatar: "🧑",
    lat: 40.758,
    lng: -73.9855,
    status: "online",
    bio: "Fitness enthusiast & designer fashion lover",
    lastSeen: "Now",
    distance: "0.2 mi",
  },
  {
    id: "2",
    username: "jordan_k",
    avatar: "👤",
    lat: 40.7614,
    lng: -73.9776,
    status: "online",
    bio: "Streetwear collector, gym regular",
    lastSeen: "Now",
    distance: "0.5 mi",
  },
  {
    id: "3",
    username: "sam_r",
    avatar: "🧑‍🦱",
    lat: 40.7549,
    lng: -73.984,
    status: "idle",
    bio: "Running coach, athleisure obsessed",
    lastSeen: "5m ago",
    distance: "0.8 mi",
  },
  {
    id: "4",
    username: "taylor_b",
    avatar: "🧔",
    lat: 40.7484,
    lng: -73.9857,
    status: "online",
    bio: "Fashion designer, body positive advocate",
    lastSeen: "Now",
    distance: "1.1 mi",
  },
  {
    id: "5",
    username: "chris_v",
    avatar: "👱",
    lat: 40.7527,
    lng: -73.9772,
    status: "online",
    bio: "Yoga instructor, wellness coach",
    lastSeen: "Now",
    distance: "0.3 mi",
  },
  {
    id: "6",
    username: "riley_n",
    avatar: "🧑‍🦰",
    lat: 40.759,
    lng: -73.971,
    status: "idle",
    bio: "Marathon runner, supplement nerd",
    lastSeen: "12m ago",
    distance: "1.5 mi",
  },
  {
    id: "7",
    username: "morgan_d",
    avatar: "👩",
    lat: 40.765,
    lng: -73.98,
    status: "online",
    bio: "Personal trainer, streetwear vibes",
    lastSeen: "Now",
    distance: "0.7 mi",
  },
  {
    id: "8",
    username: "casey_l",
    avatar: "🧑‍🎤",
    lat: 40.7505,
    lng: -73.9934,
    status: "offline",
    bio: "Lingerie boutique owner",
    lastSeen: "1h ago",
    distance: "2.0 mi",
  },
  {
    id: "9",
    username: "drew_h",
    avatar: "🧑‍💼",
    lat: 40.7425,
    lng: -73.9885,
    status: "online",
    bio: "CrossFit athlete, nutrition guru",
    lastSeen: "Now",
    distance: "1.3 mi",
  },
  {
    id: "10",
    username: "jamie_p",
    avatar: "👨‍🎨",
    lat: 40.756,
    lng: -73.99,
    status: "online",
    bio: "Custom clothier, body art enthusiast",
    lastSeen: "Now",
    distance: "0.4 mi",
  },
];

export const DESIGNER_PRODUCTS: Product[] = [
  {
    id: "d1",
    name: "Midnight Silk Bomber Jacket",
    price: 289,
    image: "🧥",
    category: "Outerwear",
    shop: "designer",
    description: "Hand-stitched silk bomber with custom lining",
    rating: 4.8,
    reviews: 124,
    badge: "New",
    colors: ["Black", "Navy", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "d2",
    name: "Tailored Linen Trousers",
    price: 185,
    image: "👖",
    category: "Bottoms",
    shop: "designer",
    description: "Italian linen, slim-fit with hidden stretch",
    rating: 4.7,
    reviews: 89,
    colors: ["Cream", "Olive", "Charcoal"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "d3",
    name: "Oversized Cashmere Hoodie",
    price: 345,
    image: "🧶",
    category: "Tops",
    shop: "designer",
    description: "Mongolian cashmere, relaxed unisex fit",
    rating: 4.9,
    reviews: 203,
    badge: "Bestseller",
    colors: ["Oat", "Storm", "Blush"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "d4",
    name: "Deconstructed Denim Vest",
    price: 165,
    image: "🦺",
    category: "Outerwear",
    shop: "designer",
    description: "Raw-edge selvedge denim, hand-distressed",
    rating: 4.5,
    reviews: 67,
    colors: ["Indigo", "Washed Black"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "d5",
    name: "Merino Wool Turtleneck",
    price: 210,
    image: "🧣",
    category: "Tops",
    shop: "designer",
    description: "Extra-fine merino, seamless knit construction",
    rating: 4.6,
    reviews: 156,
    colors: ["Ivory", "Black", "Camel"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "d6",
    name: "Leather Harness Belt",
    price: 120,
    image: "⛓️",
    category: "Accessories",
    shop: "designer",
    description: "Full-grain leather with brushed nickel hardware",
    rating: 4.8,
    reviews: 91,
    badge: "Limited",
    colors: ["Black", "Cognac"],
    sizes: ["S/M", "L/XL"],
  },
  {
    id: "d7",
    name: "Graphic Mesh Tank",
    price: 95,
    image: "🎽",
    category: "Tops",
    shop: "designer",
    description: "Semi-sheer performance mesh with bold print",
    rating: 4.4,
    reviews: 78,
    colors: ["White/Black", "Black/Gold"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "d8",
    name: "Structured Wide-Leg Pants",
    price: 225,
    image: "👔",
    category: "Bottoms",
    shop: "designer",
    description: "Architectural silhouette, Japanese fabric",
    rating: 4.7,
    reviews: 112,
    colors: ["Black", "Sand"],
    sizes: ["28", "30", "32", "34", "36"],
  },
];

export const INTIMATES_PRODUCTS: Product[] = [
  {
    id: "i1",
    name: "Mesh Panel Briefs",
    price: 32,
    image: "🩲",
    category: "Underwear",
    shop: "intimates",
    description: "Breathable mesh with contour pouch",
    rating: 4.6,
    reviews: 234,
    colors: ["Black", "White", "Red", "Royal Blue"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "i2",
    name: "Lace Trim Boxer Briefs",
    price: 38,
    image: "🩳",
    category: "Underwear",
    shop: "intimates",
    description: "Modal fabric with delicate lace trim",
    rating: 4.7,
    reviews: 189,
    badge: "Bestseller",
    colors: ["Black", "Midnight", "Wine"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "i3",
    name: "Sheer Bodysuit",
    price: 65,
    image: "🎀",
    category: "Bodywear",
    shop: "intimates",
    description: "Full sheer with strategic seaming",
    rating: 4.5,
    reviews: 145,
    colors: ["Black", "Nude", "Red"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "i4",
    name: "Satin Lounge Shorts",
    price: 45,
    image: "✨",
    category: "Loungewear",
    shop: "intimates",
    description: "Silk-touch satin with side split hem",
    rating: 4.8,
    reviews: 98,
    colors: ["Champagne", "Black", "Blush"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "i5",
    name: "Jockstrap Classic",
    price: 28,
    image: "💪",
    category: "Underwear",
    shop: "intimates",
    description: "Athletic-cut with wide comfort waistband",
    rating: 4.4,
    reviews: 312,
    colors: ["Black", "White", "Neon Green", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "i6",
    name: "Vibrating Massage Ring",
    price: 35,
    image: "💫",
    category: "Accessories",
    shop: "intimates",
    description: "Waterproof silicone, 10 vibration modes",
    rating: 4.7,
    reviews: 267,
    badge: "Top Rated",
  },
  {
    id: "i7",
    name: "Couples Pleasure Set",
    price: 89,
    image: "🎁",
    category: "Accessories",
    shop: "intimates",
    description: "Premium kit with massage oils and accessories",
    rating: 4.6,
    reviews: 156,
    badge: "Gift Pick",
  },
  {
    id: "i8",
    name: "Silk Sleep Mask & Robe Set",
    price: 110,
    image: "🌙",
    category: "Loungewear",
    shop: "intimates",
    description: "100% mulberry silk, matching set",
    rating: 4.9,
    reviews: 201,
    colors: ["Black", "Ivory", "Dusty Rose"],
    sizes: ["S/M", "L/XL"],
  },
];

export const ATHLETICS_PRODUCTS: Product[] = [
  {
    id: "a1",
    name: "Whey Protein Isolate 5lb",
    price: 65,
    image: "🥛",
    category: "Supplements",
    shop: "athletics",
    description: "25g protein per serving, zero sugar",
    rating: 4.8,
    reviews: 456,
    badge: "Bestseller",
  },
  {
    id: "a2",
    name: "Pre-Workout Ignite",
    price: 45,
    image: "⚡",
    category: "Supplements",
    shop: "athletics",
    description: "300mg caffeine, beta-alanine, citrulline",
    rating: 4.6,
    reviews: 334,
  },
  {
    id: "a3",
    name: "Creatine Monohydrate 500g",
    price: 30,
    image: "💊",
    category: "Supplements",
    shop: "athletics",
    description: "Micronized for fast absorption",
    rating: 4.9,
    reviews: 567,
  },
  {
    id: "a4",
    name: "Adjustable Dumbbell Set",
    price: 299,
    image: "🏋️",
    category: "Equipment",
    shop: "athletics",
    description: "5-52.5 lbs each, quick-change system",
    rating: 4.7,
    reviews: 189,
    badge: "Top Pick",
  },
  {
    id: "a5",
    name: "Resistance Band Pro Kit",
    price: 49,
    image: "🎯",
    category: "Equipment",
    shop: "athletics",
    description: "5 bands, door anchor, handles, ankle straps",
    rating: 4.5,
    reviews: 278,
  },
  {
    id: "a6",
    name: "Compression Leggings",
    price: 68,
    image: "🦿",
    category: "Apparel",
    shop: "athletics",
    description: "Graduated compression, moisture-wicking",
    rating: 4.6,
    reviews: 345,
    colors: ["Black", "Navy", "Camo"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "a7",
    name: "BCAA Recovery Powder",
    price: 35,
    image: "🧪",
    category: "Supplements",
    shop: "athletics",
    description: "2:1:1 ratio, electrolytes, zero calories",
    rating: 4.5,
    reviews: 223,
  },
  {
    id: "a8",
    name: "Olympic Barbell 7ft",
    price: 199,
    image: "🔩",
    category: "Equipment",
    shop: "athletics",
    description: "Chrome-plated steel, 700lb capacity",
    rating: 4.8,
    reviews: 134,
  },
  {
    id: "a9",
    name: "Multivitamin Daily Pack",
    price: 40,
    image: "💎",
    category: "Supplements",
    shop: "athletics",
    description: "AM/PM packs, 30-day supply",
    rating: 4.7,
    reviews: 412,
  },
  {
    id: "a10",
    name: "Smart Jump Rope",
    price: 55,
    image: "🔄",
    category: "Equipment",
    shop: "athletics",
    description: "LED counter, adjustable length, weighted handles",
    rating: 4.4,
    reviews: 167,
  },
];

export const MERCHANT_STATS: MerchantStats = {
  totalRevenue: 284750,
  totalOrders: 3842,
  totalProducts: 26,
  conversionRate: 4.7,
  avgOrderValue: 74.12,
  monthlyGrowth: 12.3,
};

export const MONTHLY_REVENUE = [
  { month: "Jan", designer: 18200, intimates: 12400, athletics: 15800 },
  { month: "Feb", designer: 19500, intimates: 14200, athletics: 16900 },
  { month: "Mar", designer: 22100, intimates: 15800, athletics: 19200 },
  { month: "Apr", designer: 24300, intimates: 16500, athletics: 21400 },
  { month: "May", designer: 26800, intimates: 18900, athletics: 23100 },
  { month: "Jun", designer: 28500, intimates: 20100, athletics: 25600 },
];
