import type {
  Repository,
  ClusterHealth,
  DeploymentConfig,
  DeploymentEvent,
  Wallet,
  Transaction,
  RevenueMetrics,
  PaymentConfig,
  FundAllocation,
  GrantVerification,
  Asset,
  AssetClaim,
  SecurityScan,
  Vulnerability,
  ComplianceStatus,
  AutomationWorkflow,
  Notification,
  AuditLogEntry,
  PlatformOverview,
} from "./types";

// ─── Repository Registry (all 22 repos) ──────────────────────────────────────

export const REPOSITORIES: Repository[] = [
  {
    id: "repo-1",
    name: "Supervisor",
    fullName: "jacob-soto/Supervisor",
    description:
      "AWS ECS/ECR deployment infrastructure and Super-App ecosystem",
    language: "Go/TypeScript",
    url: "https://github.com/jacob-soto/Supervisor",
    deploymentTarget: "aws-ecs",
    status: "active",
    lastDeployed: "2025-05-24T18:30:00Z",
    environment: "production",
  },
  {
    id: "repo-2",
    name: "kubectl-ai",
    fullName: "jacob-soto/kubectl-ai",
    description: "Kubernetes orchestration and AI-powered automation CLI",
    language: "Go",
    url: "https://github.com/jacob-soto/kubectl-ai",
    deploymentTarget: "kubernetes",
    status: "active",
    lastDeployed: "2025-05-24T16:00:00Z",
    environment: "production",
  },
  {
    id: "repo-3",
    name: "nationalsecurityagency.github.io",
    fullName: "jacob-soto/nationalsecurityagency.github.io",
    description: "Terraform IaC foundation and NSA open-source portal",
    language: "Jekyll/Terraform",
    url: "https://github.com/jacob-soto/nationalsecurityagency.github.io",
    deploymentTarget: "static",
    status: "active",
    lastDeployed: "2025-05-23T12:00:00Z",
    environment: "production",
  },
  {
    id: "repo-4",
    name: "nextjs-commerce",
    fullName: "jacob-soto/nextjs-commerce",
    description: "E-commerce platform base with Shopify integration",
    language: "TypeScript",
    url: "https://github.com/jacob-soto/nextjs-commerce",
    deploymentTarget: "vercel",
    status: "active",
    lastDeployed: "2025-05-25T01:00:00Z",
    environment: "production",
  },
  {
    id: "repo-5",
    name: "merchant-sdk-php",
    fullName: "jacob-soto/merchant-sdk-php",
    description: "PayPal Classic API payment processing SDK",
    language: "PHP",
    url: "https://github.com/jacob-soto/merchant-sdk-php",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-6",
    name: "dev-grid",
    fullName: "jacob-soto/dev-grid",
    description: "Financial management and agent dashboard system",
    language: "TypeScript/React",
    url: "https://github.com/jacob-soto/dev-grid",
    deploymentTarget: "vercel",
    status: "active",
    lastDeployed: "2025-05-24T20:00:00Z",
    environment: "production",
  },
  {
    id: "repo-7",
    name: "Jacob-Soto-The-commission-on-human-rights-pro-hac-vice",
    fullName:
      "jacob-soto/Jacob-Soto-The-commission-on-human-rights-pro-hac-vice",
    description: "PHANTOM-NET asset tracking and legal discovery system",
    language: "TypeScript/React",
    url: "https://github.com/jacob-soto/Jacob-Soto-The-commission-on-human-rights-pro-hac-vice",
    deploymentTarget: "vercel",
    status: "active",
    lastDeployed: "2025-05-24T22:00:00Z",
    environment: "production",
  },
  {
    id: "repo-8",
    name: "kev-data",
    fullName: "jacob-soto/kev-data",
    description: "CISA Known Exploited Vulnerabilities catalog mirror",
    language: "JSON/Shell",
    url: "https://github.com/jacob-soto/kev-data",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-9",
    name: "cyber.dhs.gov",
    fullName: "jacob-soto/cyber.dhs.gov",
    description: "CISA cybersecurity directives and compliance documentation",
    language: "Jekyll/Ruby",
    url: "https://github.com/jacob-soto/cyber.dhs.gov",
    deploymentTarget: "static",
    status: "active",
    lastDeployed: "2025-05-22T10:00:00Z",
    environment: "production",
  },
  {
    id: "repo-10",
    name: "Argus-Advanced-Sentinel",
    fullName: "jacob-soto/Argus-Advanced-Sentinel",
    description: "ARGUS AI assistant with Gemini integration",
    language: "TypeScript/React",
    url: "https://github.com/jacob-soto/Argus-Advanced-Sentinel",
    deploymentTarget: "vercel",
    status: "active",
    lastDeployed: "2025-05-24T14:00:00Z",
    environment: "production",
  },
  {
    id: "repo-11",
    name: "fast-glob",
    fullName: "jacob-soto/fast-glob",
    description: "High-performance glob pattern file system traversal",
    language: "TypeScript",
    url: "https://github.com/jacob-soto/fast-glob",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-12",
    name: "icsnpp-baycnet",
    fullName: "jacob-soto/icsnpp-baycnet",
    description: "Zeek BACnet ICS protocol parser plugin",
    language: "C++/Zeek",
    url: "https://github.com/jacob-soto/icsnpp-baycnet",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-13",
    name: "jackit1",
    fullName: "jacob-soto/jackit1",
    description: "Project root and documentation anchor",
    language: "Markdown",
    url: "https://github.com/jacob-soto/jackit1",
    deploymentTarget: "none",
    status: "inactive",
    lastDeployed: null,
    environment: "development",
  },
  {
    id: "repo-14",
    name: "Linux-nycha-via",
    fullName: "jacob-soto/Linux-nycha-via",
    description: "AI Studio ecosystem entry point",
    language: "Markdown",
    url: "https://github.com/jacob-soto/Linux-nycha-via",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "development",
  },
  {
    id: "repo-15",
    name: "mapping-neighborhoods",
    fullName:
      "jacob-soto/mapping-neighborhoods-highest-risk-housing-instability-and-homelessness",
    description: "ERAP Index 2.0 geospatial visualization",
    language: "Svelte/JavaScript",
    url: "https://github.com/jacob-soto/mapping-neighborhoods-highest-risk-housing-instability-and-homelessness",
    deploymentTarget: "vercel",
    status: "active",
    lastDeployed: "2025-05-20T08:00:00Z",
    environment: "production",
  },
  {
    id: "repo-16",
    name: "maria",
    fullName: "jacob-soto/maria",
    description: "MCP server for Cloudflare Workers",
    language: "TypeScript",
    url: "https://github.com/jacob-soto/maria",
    deploymentTarget: "kubernetes",
    status: "active",
    lastDeployed: "2025-05-23T16:00:00Z",
    environment: "production",
  },
  {
    id: "repo-17",
    name: "my-nexus-app",
    fullName: "jacob-soto/my-nexus-app",
    description: "Document extraction and ingestion pipeline",
    language: "Python/React",
    url: "https://github.com/jacob-soto/my-nexus-app",
    deploymentTarget: "kubernetes",
    status: "active",
    lastDeployed: "2025-05-22T14:00:00Z",
    environment: "staging",
  },
  {
    id: "repo-18",
    name: "nextjs-preview-mode",
    fullName: "jacob-soto/nextjs-preview-mode",
    description: "Next.js hybrid rendering preview mode demo",
    language: "TypeScript",
    url: "https://github.com/jacob-soto/nextjs-preview-mode",
    deploymentTarget: "vercel",
    status: "active",
    lastDeployed: "2025-05-21T10:00:00Z",
    environment: "staging",
  },
  {
    id: "repo-19",
    name: "shareable-soar-workflows",
    fullName: "jacob-soto/shareable-soar-workflows",
    description: "SOAR security automation workflows (BPMN)",
    language: "XML/BPMN",
    url: "https://github.com/jacob-soto/shareable-soar-workflows",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-20",
    name: "tavily-python",
    fullName: "jacob-soto/tavily-python",
    description: "Tavily API Python SDK for AI search",
    language: "Python",
    url: "https://github.com/jacob-soto/tavily-python",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-21",
    name: "Termux-",
    fullName: "jacob-soto/Termux-",
    description: "Android terminal emulator and Linux environment",
    language: "Java/Smali",
    url: "https://github.com/jacob-soto/Termux-",
    deploymentTarget: "none",
    status: "active",
    lastDeployed: null,
    environment: "production",
  },
  {
    id: "repo-22",
    name: "WALKOFF",
    fullName: "jacob-soto/WALKOFF",
    description: "Security orchestration and automation framework",
    language: "Python",
    url: "https://github.com/jacob-soto/WALKOFF",
    deploymentTarget: "kubernetes",
    status: "active",
    lastDeployed: "2025-05-23T20:00:00Z",
    environment: "production",
  },
];

// ─── Cluster Health ───────────────────────────────────────────────────────────

export const CLUSTERS: ClusterHealth[] = [
  {
    id: "cluster-1",
    name: "OlympusNET-ECS",
    provider: "aws-ecs",
    region: "us-east-2",
    status: "healthy",
    nodesTotal: 6,
    nodesReady: 6,
    podsRunning: 12,
    podsDesired: 12,
    cpuUtilization: 42,
    memoryUtilization: 58,
    lastChecked: "2025-05-25T01:15:00Z",
  },
  {
    id: "cluster-2",
    name: "kubectl-ai-primary",
    provider: "kubernetes",
    region: "us-west-2",
    status: "healthy",
    nodesTotal: 4,
    nodesReady: 4,
    podsRunning: 18,
    podsDesired: 18,
    cpuUtilization: 35,
    memoryUtilization: 51,
    lastChecked: "2025-05-25T01:15:00Z",
  },
  {
    id: "cluster-3",
    name: "walkoff-cluster",
    provider: "kubernetes",
    region: "us-east-1",
    status: "degraded",
    nodesTotal: 3,
    nodesReady: 2,
    podsRunning: 8,
    podsDesired: 10,
    cpuUtilization: 78,
    memoryUtilization: 72,
    lastChecked: "2025-05-25T01:15:00Z",
  },
  {
    id: "cluster-4",
    name: "maria-workers",
    provider: "kubernetes",
    region: "eu-west-1",
    status: "healthy",
    nodesTotal: 2,
    nodesReady: 2,
    podsRunning: 6,
    podsDesired: 6,
    cpuUtilization: 28,
    memoryUtilization: 40,
    lastChecked: "2025-05-25T01:15:00Z",
  },
  {
    id: "cluster-5",
    name: "nexus-gke-primary",
    provider: "gcp-gke",
    region: "us-central1",
    status: "healthy",
    nodesTotal: 5,
    nodesReady: 5,
    podsRunning: 14,
    podsDesired: 14,
    cpuUtilization: 38,
    memoryUtilization: 52,
    lastChecked: "2025-05-25T01:15:00Z",
  },
  {
    id: "cluster-6",
    name: "nexus-cloudrun",
    provider: "gcp-cloudrun",
    region: "us-east4",
    status: "healthy",
    nodesTotal: 0,
    nodesReady: 0,
    podsRunning: 8,
    podsDesired: 8,
    cpuUtilization: 22,
    memoryUtilization: 34,
    lastChecked: "2025-05-25T01:15:00Z",
  },
];

// ─── Deployment Configs ───────────────────────────────────────────────────────

export const DEPLOYMENTS: DeploymentConfig[] = [
  {
    id: "dep-1",
    repoId: "repo-1",
    target: "aws-ecs",
    environment: "production",
    strategy: "blue-green",
    status: "healthy",
    region: "us-east-2",
    cluster: "OlympusNET-ECS",
    service: "supervisor-service",
    taskDefinition: "supervisor-task:14",
    containerName: "olympus_net_sphere",
    lastDeployedAt: "2025-05-24T18:30:00Z",
    lastDeployedBy: "github-actions",
  },
  {
    id: "dep-2",
    repoId: "repo-2",
    target: "kubernetes",
    environment: "production",
    strategy: "rolling",
    status: "healthy",
    region: "us-west-2",
    cluster: "kubectl-ai-primary",
    service: "kubectl-ai-svc",
    taskDefinition: "kubectl-ai-deploy",
    containerName: "kubectl-ai",
    lastDeployedAt: "2025-05-24T16:00:00Z",
    lastDeployedBy: "github-actions",
  },
  {
    id: "dep-3",
    repoId: "repo-22",
    target: "kubernetes",
    environment: "production",
    strategy: "rolling",
    status: "healthy",
    region: "us-east-1",
    cluster: "walkoff-cluster",
    service: "walkoff-api",
    taskDefinition: "walkoff-deploy",
    containerName: "walkoff-api",
    lastDeployedAt: "2025-05-23T20:00:00Z",
    lastDeployedBy: "github-actions",
  },
  {
    id: "dep-4",
    repoId: "repo-16",
    target: "kubernetes",
    environment: "production",
    strategy: "canary",
    status: "healthy",
    region: "eu-west-1",
    cluster: "maria-workers",
    service: "maria-mcp",
    taskDefinition: "maria-deploy",
    containerName: "maria-worker",
    lastDeployedAt: "2025-05-23T16:00:00Z",
    lastDeployedBy: "github-actions",
  },
  {
    id: "dep-5",
    repoId: "repo-1",
    target: "aws-ecs",
    environment: "staging",
    strategy: "rolling",
    status: "healthy",
    region: "us-east-2",
    cluster: "OlympusNET-ECS",
    service: "supervisor-staging",
    taskDefinition: "supervisor-task:15",
    containerName: "olympus_net_sphere",
    lastDeployedAt: "2025-05-25T00:30:00Z",
    lastDeployedBy: "github-actions",
  },
  {
    id: "dep-6",
    repoId: "repo-4",
    target: "gcp-cloudrun",
    environment: "production",
    strategy: "canary",
    status: "healthy",
    region: "us-east4",
    cluster: "nexus-cloudrun",
    service: "nextjs-commerce-prod",
    taskDefinition: "nextjs-commerce-rev-42",
    containerName: "nextjs-commerce",
    lastDeployedAt: "2025-05-25T01:00:00Z",
    lastDeployedBy: "cloud-build",
  },
  {
    id: "dep-7",
    repoId: "repo-10",
    target: "gcp-gke",
    environment: "production",
    strategy: "rolling",
    status: "healthy",
    region: "us-central1",
    cluster: "nexus-gke-primary",
    service: "argus-sentinel-svc",
    taskDefinition: "argus-deploy-v8",
    containerName: "argus-sentinel",
    lastDeployedAt: "2025-05-24T14:00:00Z",
    lastDeployedBy: "cloud-build",
  },
  {
    id: "dep-8",
    repoId: "repo-17",
    target: "gcp-gke",
    environment: "staging",
    strategy: "rolling",
    status: "healthy",
    region: "us-central1",
    cluster: "nexus-gke-primary",
    service: "nexus-app-staging",
    taskDefinition: "nexus-app-deploy-v3",
    containerName: "nexus-app",
    lastDeployedAt: "2025-05-22T14:00:00Z",
    lastDeployedBy: "cloud-build",
  },
];

// ─── Deployment Events ────────────────────────────────────────────────────────

export const DEPLOYMENT_EVENTS: DeploymentEvent[] = [
  {
    id: "evt-1",
    deploymentId: "dep-1",
    timestamp: "2025-05-24T18:30:00Z",
    type: "success",
    message:
      "Blue-green deployment completed. Traffic switched to new task set.",
  },
  {
    id: "evt-2",
    deploymentId: "dep-1",
    timestamp: "2025-05-24T18:28:00Z",
    type: "info",
    message: "New task set reached steady state. Health checks passing.",
  },
  {
    id: "evt-3",
    deploymentId: "dep-2",
    timestamp: "2025-05-24T16:00:00Z",
    type: "success",
    message: "Rolling update completed. All pods healthy.",
  },
  {
    id: "evt-4",
    deploymentId: "dep-3",
    timestamp: "2025-05-23T20:05:00Z",
    type: "warning",
    message: "Node walkoff-node-3 reporting high memory pressure.",
  },
  {
    id: "evt-5",
    deploymentId: "dep-5",
    timestamp: "2025-05-25T00:30:00Z",
    type: "success",
    message: "Staging deployment completed. Running integration tests.",
  },
  {
    id: "evt-6",
    deploymentId: "dep-6",
    timestamp: "2025-05-25T01:00:00Z",
    type: "success",
    message:
      "Cloud Run revision deployed. Canary traffic split: 90/10 → 100/0.",
  },
  {
    id: "evt-7",
    deploymentId: "dep-7",
    timestamp: "2025-05-24T14:00:00Z",
    type: "success",
    message:
      "GKE rolling update completed. All replicas healthy on nexus-gke-primary.",
  },
  {
    id: "evt-8",
    deploymentId: "dep-8",
    timestamp: "2025-05-22T14:05:00Z",
    type: "info",
    message:
      "GKE staging deployment stabilized. Turbopack build completed in 4.2s.",
  },
];

// ─── Revenue & Treasury ───────────────────────────────────────────────────────

export const TREASURY: Wallet = {
  balance: 2847500.0,
  transactions: [
    {
      id: "T-8K2MN4PQ",
      timestamp: "2025-05-24T22:00:00Z",
      description: "PayPal Express Checkout — Platform License",
      amount: 12500,
      balance: 2847500,
      source: "paypal",
      category: "income",
    },
    {
      id: "T-7L3NO5RS",
      timestamp: "2025-05-24T18:00:00Z",
      description: "Operational Allocation: Infrastructure Scaling",
      amount: -4200,
      balance: 2835000,
      source: "allocation",
      category: "allocation",
    },
    {
      id: "T-6M4OP6TU",
      timestamp: "2025-05-24T14:00:00Z",
      description: "Grant Disbursement: Federal Cybersecurity Initiative",
      amount: 75000,
      balance: 2839200,
      source: "grant",
      category: "grant",
    },
    {
      id: "T-5N5PQ7UV",
      timestamp: "2025-05-24T10:00:00Z",
      description: "Asset Recovery: Digital Certificate Valuation",
      amount: 18000,
      balance: 2764200,
      source: "asset-recovery",
      category: "recovery",
    },
    {
      id: "T-4O6QR8WX",
      timestamp: "2025-05-23T20:00:00Z",
      description: "Platform Fee Revenue: API Access Tier 2",
      amount: 8500,
      balance: 2746200,
      source: "platform-fees",
      category: "income",
    },
    {
      id: "T-3P7RS9YZ",
      timestamp: "2025-05-23T16:00:00Z",
      description: "Spot Funding: Emergency Security Patch Deployment",
      amount: 25000,
      balance: 2737700,
      source: "spot-funding",
      category: "income",
    },
    {
      id: "T-2Q8ST0AB",
      timestamp: "2025-05-23T12:00:00Z",
      description: "PayPal Recurring Payment — Enterprise Subscription",
      amount: 45000,
      balance: 2712700,
      source: "paypal",
      category: "income",
    },
    {
      id: "T-1R9TU1CD",
      timestamp: "2025-05-23T08:00:00Z",
      description: "Operational Allocation: Security Audit",
      amount: -15000,
      balance: 2667700,
      source: "allocation",
      category: "allocation",
    },
  ],
};

export const REVENUE_METRICS: RevenueMetrics = {
  totalRevenue: 14582400,
  monthlyRevenue: 847500,
  pendingPayments: 125000,
  activeSubscriptions: 342,
  revenueBySource: {
    paypal: 4250000,
    stripe: 3180000,
    grant: 2750000,
    "asset-recovery": 1850000,
    "platform-fees": 1420000,
    allocation: 0,
    "spot-funding": 1132400,
  },
  monthlyTrend: [
    { month: "Dec 2024", revenue: 620000, expenses: 180000 },
    { month: "Jan 2025", revenue: 710000, expenses: 195000 },
    { month: "Feb 2025", revenue: 680000, expenses: 172000 },
    { month: "Mar 2025", revenue: 750000, expenses: 210000 },
    { month: "Apr 2025", revenue: 820000, expenses: 198000 },
    { month: "May 2025", revenue: 847500, expenses: 215000 },
  ],
};

export const PAYMENT_CONFIGS: PaymentConfig[] = [
  {
    provider: "paypal",
    mode: "live",
    clientId: "PAYPAL_CLIENT_****",
    configured: true,
  },
  {
    provider: "stripe",
    mode: "live",
    clientId: "STRIPE_PK_****",
    configured: true,
  },
];

export const FUND_ALLOCATIONS: FundAllocation[] = [
  {
    id: "alloc-1",
    amount: 4200,
    reason: "Infrastructure Scaling — Additional ECS Capacity",
    status: "disbursed",
    requestedAt: "2025-05-24T17:00:00Z",
    approvedAt: "2025-05-24T17:30:00Z",
    approvedBy: "admin",
  },
  {
    id: "alloc-2",
    amount: 15000,
    reason: "Security Audit — Annual Compliance Review",
    status: "disbursed",
    requestedAt: "2025-05-23T11:00:00Z",
    approvedAt: "2025-05-23T11:30:00Z",
    approvedBy: "admin",
  },
  {
    id: "alloc-3",
    amount: 8500,
    reason: "Emergency Hotfix Deployment — Critical CVE Patch",
    status: "pending",
    requestedAt: "2025-05-25T00:00:00Z",
    approvedAt: null,
    approvedBy: null,
  },
];

export const GRANT_VERIFICATIONS: GrantVerification[] = [
  {
    id: "grant-1",
    grantName: "Federal Cybersecurity Initiative Fund",
    status: "verified",
    amount: 75000,
    verifiedAt: "2025-05-24T13:00:00Z",
    source: "DHS/CISA",
  },
  {
    id: "grant-2",
    grantName: "Open Source Security Foundation Grant",
    status: "pending",
    amount: 50000,
    verifiedAt: null,
    source: "OpenSSF",
  },
  {
    id: "grant-3",
    grantName: "Digital Infrastructure Modernization",
    status: "verified",
    amount: 120000,
    verifiedAt: "2025-05-20T10:00:00Z",
    source: "GSA",
  },
];

// ─── Asset Management ─────────────────────────────────────────────────────────

export const ASSETS: Asset[] = [
  {
    id: "asset-1",
    name: "OlympusNET Production Cluster",
    type: "compute",
    status: "active",
    value: "$24,000/mo",
    description: "AWS ECS cluster running Supervisor infrastructure",
    deployedAt: "2025-01-15T00:00:00Z",
    lastUpdated: "2025-05-24T18:30:00Z",
    owner: "platform-admin",
    accessLevel: "admin",
    metadata: { region: "us-east-2", provider: "AWS" },
  },
  {
    id: "asset-2",
    name: "kubectl-ai Kubernetes Cluster",
    type: "compute",
    status: "active",
    value: "$18,000/mo",
    description: "Primary K8s cluster for AI orchestration",
    deployedAt: "2025-02-01T00:00:00Z",
    lastUpdated: "2025-05-24T16:00:00Z",
    owner: "platform-admin",
    accessLevel: "admin",
    metadata: { region: "us-west-2", provider: "AWS" },
  },
  {
    id: "asset-3",
    name: "Platform API Keys Bundle",
    type: "api-key",
    status: "active",
    value: "N/A",
    description: "Managed API keys for Shopify, PayPal, Gemini integrations",
    deployedAt: null,
    lastUpdated: "2025-05-24T12:00:00Z",
    owner: "platform-admin",
    accessLevel: "admin",
    metadata: { count: "12" },
  },
  {
    id: "asset-4",
    name: "Legal Discovery Database",
    type: "database",
    status: "active",
    value: "$2,400/mo",
    description: "PostgreSQL instance for PHANTOM-NET evidence and filings",
    deployedAt: "2025-03-01T00:00:00Z",
    lastUpdated: "2025-05-24T22:00:00Z",
    owner: "legal-team",
    accessLevel: "admin",
    metadata: { engine: "PostgreSQL 15", size: "500GB" },
  },
  {
    id: "asset-5",
    name: "CDN & Static Assets",
    type: "storage",
    status: "active",
    value: "$3,200/mo",
    description: "CloudFront distribution for static sites and assets",
    deployedAt: "2025-01-01T00:00:00Z",
    lastUpdated: "2025-05-23T12:00:00Z",
    owner: "platform-admin",
    accessLevel: "developer",
    metadata: { provider: "CloudFront", regions: "Global" },
  },
  {
    id: "asset-6",
    name: "TLS Wildcard Certificate",
    type: "certificate",
    status: "active",
    value: "$500/yr",
    description: "Wildcard TLS certificate for *.platform.io",
    deployedAt: "2025-01-01T00:00:00Z",
    lastUpdated: "2025-05-01T00:00:00Z",
    owner: "security-team",
    accessLevel: "admin",
    metadata: { issuer: "Let's Encrypt", expires: "2025-12-31" },
  },
  {
    id: "asset-7",
    name: "platform.io Domain",
    type: "domain",
    status: "active",
    value: "$12/yr",
    description: "Primary platform domain registration",
    deployedAt: null,
    lastUpdated: "2025-01-01T00:00:00Z",
    owner: "platform-admin",
    accessLevel: "admin",
    metadata: { registrar: "Cloudflare", expires: "2026-01-01" },
  },
];

export const ASSET_CLAIMS: AssetClaim[] = [
  {
    id: "claim-1",
    label: "Pending Justice Settlement",
    amount: "RELEASE_PENDING",
    status: "blocked",
    filingId: "fil_1",
    lastUpdated: "2025-05-24T22:00:00Z",
  },
  {
    id: "claim-2",
    label: "Total Assets Stolen via Impersonation",
    amount: "$10,240,000,000",
    status: "under_investigation",
    filingId: "fil_3",
    lastUpdated: "2025-05-24T20:00:00Z",
  },
  {
    id: "claim-3",
    label: "Digital Asset Recovery — Certificate Fraud",
    amount: "$450,000",
    status: "pending",
    filingId: null,
    lastUpdated: "2025-05-23T14:00:00Z",
  },
];

// ─── Security & Compliance ────────────────────────────────────────────────────

export const SECURITY_SCANS: SecurityScan[] = [
  {
    id: "scan-1",
    repoId: "repo-1",
    repoName: "Supervisor",
    status: "completed",
    startedAt: "2025-05-24T20:00:00Z",
    completedAt: "2025-05-24T20:15:00Z",
    vulnerabilitiesFound: 3,
    criticalCount: 0,
    highCount: 1,
    mediumCount: 1,
    lowCount: 1,
  },
  {
    id: "scan-2",
    repoId: "repo-2",
    repoName: "kubectl-ai",
    status: "completed",
    startedAt: "2025-05-24T20:00:00Z",
    completedAt: "2025-05-24T20:12:00Z",
    vulnerabilitiesFound: 1,
    criticalCount: 0,
    highCount: 0,
    mediumCount: 1,
    lowCount: 0,
  },
  {
    id: "scan-3",
    repoId: "repo-22",
    repoName: "WALKOFF",
    status: "completed",
    startedAt: "2025-05-24T20:00:00Z",
    completedAt: "2025-05-24T20:20:00Z",
    vulnerabilitiesFound: 7,
    criticalCount: 1,
    highCount: 2,
    mediumCount: 3,
    lowCount: 1,
  },
  {
    id: "scan-4",
    repoId: "repo-4",
    repoName: "nextjs-commerce",
    status: "scanning",
    startedAt: "2025-05-25T01:00:00Z",
    completedAt: null,
    vulnerabilitiesFound: 0,
    criticalCount: 0,
    highCount: 0,
    mediumCount: 0,
    lowCount: 0,
  },
  {
    id: "scan-5",
    repoId: "repo-6",
    repoName: "dev-grid",
    status: "completed",
    startedAt: "2025-05-24T20:00:00Z",
    completedAt: "2025-05-24T20:10:00Z",
    vulnerabilitiesFound: 2,
    criticalCount: 0,
    highCount: 0,
    mediumCount: 2,
    lowCount: 0,
  },
];

export const KEV_SAMPLE: Vulnerability[] = [
  {
    cveID: "CVE-2021-26829",
    vendorProject: "OpenPLC",
    product: "ScadaBR",
    vulnerabilityName: "OpenPLC ScadaBR Cross-site Scripting Vulnerability",
    dateAdded: "2025-11-28",
    shortDescription:
      "OpenPLC ScadaBR contains a cross-site scripting vulnerability.",
    requiredAction:
      "Apply mitigations per vendor instructions or discontinue use.",
    dueDate: "2025-12-19",
    knownRansomwareCampaignUse: "Unknown",
    cwes: ["CWE-79"],
  },
  {
    cveID: "CVE-2025-61757",
    vendorProject: "Oracle",
    product: "Fusion Middleware",
    vulnerabilityName:
      "Oracle Fusion Middleware Missing Authentication Vulnerability",
    dateAdded: "2025-11-21",
    shortDescription:
      "Missing authentication for critical function vulnerability.",
    requiredAction: "Apply mitigations per vendor instructions.",
    dueDate: "2025-12-12",
    knownRansomwareCampaignUse: "Unknown",
    cwes: ["CWE-306"],
  },
  {
    cveID: "CVE-2025-13223",
    vendorProject: "Google",
    product: "Chromium V8",
    vulnerabilityName: "Google Chromium V8 Type Confusion Vulnerability",
    dateAdded: "2025-11-19",
    shortDescription: "Type confusion vulnerability allowing heap corruption.",
    requiredAction: "Apply mitigations per vendor instructions.",
    dueDate: "2025-12-10",
    knownRansomwareCampaignUse: "Unknown",
    cwes: ["CWE-843"],
  },
];

export const COMPLIANCE_STATUSES: ComplianceStatus[] = [
  {
    directive: "BOD 18-02",
    title: "Securing High Value Assets",
    status: "compliant",
    lastAssessed: "2025-05-20T00:00:00Z",
    dueDate: null,
    requirements: [
      {
        id: "req-1",
        description: "Identify and inventory all high value assets",
        status: "met",
        evidence: "Asset inventory completed — 7 HVAs identified",
      },
      {
        id: "req-2",
        description: "Implement enhanced security measures for HVAs",
        status: "met",
        evidence: "MFA, encryption at rest, network segmentation active",
      },
      {
        id: "req-3",
        description: "Report HVA assessments to DHS",
        status: "met",
        evidence: "Quarterly report submitted 2025-Q1",
      },
    ],
  },
  {
    directive: "BOD 22-01",
    title: "Reducing Known Exploited Vulnerabilities",
    status: "in-progress",
    lastAssessed: "2025-05-24T00:00:00Z",
    dueDate: "2025-12-19",
    requirements: [
      {
        id: "req-4",
        description: "Remediate all KEV catalog entries within timelines",
        status: "partial",
        evidence: "1,461/1,464 vulnerabilities addressed",
      },
      {
        id: "req-5",
        description: "Implement automated KEV scanning",
        status: "met",
        evidence: "Hourly sync from CISA KEV catalog via kev-data",
      },
      {
        id: "req-6",
        description: "Report remediation status via CDM dashboard",
        status: "met",
        evidence: "Auto-reporting configured",
      },
    ],
  },
  {
    directive: "BOD 18-01",
    title: "Email and Web Security (DMARC/HTTPS)",
    status: "compliant",
    lastAssessed: "2025-05-15T00:00:00Z",
    dueDate: null,
    requirements: [
      {
        id: "req-7",
        description: "Implement DMARC with p=reject on all domains",
        status: "met",
        evidence: "All 3 domains configured with p=reject",
      },
      {
        id: "req-8",
        description: "Enable HSTS preloading on all web properties",
        status: "met",
        evidence: "HSTS headers present, preload list submitted",
      },
      {
        id: "req-9",
        description: "Configure SPF and DKIM for all email domains",
        status: "met",
        evidence: "SPF and DKIM records verified",
      },
    ],
  },
];

// ─── Automation Workflows ─────────────────────────────────────────────────────

export const WORKFLOWS: AutomationWorkflow[] = [
  {
    id: "wf-1",
    name: "Multi-Repo Deployment Pipeline",
    description: "Automated deployment across AWS ECS and Kubernetes clusters",
    type: "deployment",
    status: "active",
    schedule: "0 */6 * * *",
    lastRun: "2025-05-25T00:00:00Z",
    nextRun: "2025-05-25T06:00:00Z",
    triggerType: "schedule",
    steps: [
      {
        id: "step-1",
        name: "Pull latest changes",
        type: "git",
        status: "completed",
        startedAt: "2025-05-25T00:00:00Z",
        completedAt: "2025-05-25T00:01:00Z",
        output: "22 repos checked, 3 with changes",
      },
      {
        id: "step-2",
        name: "Run test suites",
        type: "test",
        status: "completed",
        startedAt: "2025-05-25T00:01:00Z",
        completedAt: "2025-05-25T00:05:00Z",
        output: "All tests passed",
      },
      {
        id: "step-3",
        name: "Build container images",
        type: "build",
        status: "completed",
        startedAt: "2025-05-25T00:05:00Z",
        completedAt: "2025-05-25T00:10:00Z",
        output: "3 images built and pushed to ECR",
      },
      {
        id: "step-4",
        name: "Deploy to staging",
        type: "deploy",
        status: "completed",
        startedAt: "2025-05-25T00:10:00Z",
        completedAt: "2025-05-25T00:15:00Z",
        output: "Staging deployments healthy",
      },
      {
        id: "step-5",
        name: "Deploy to production",
        type: "deploy",
        status: "completed",
        startedAt: "2025-05-25T00:15:00Z",
        completedAt: "2025-05-25T00:20:00Z",
        output: "Production blue-green switch complete",
      },
    ],
  },
  {
    id: "wf-2",
    name: "Revenue Reconciliation",
    description: "Daily reconciliation of PayPal, Stripe, and grant revenues",
    type: "revenue-reconciliation",
    status: "active",
    schedule: "0 2 * * *",
    lastRun: "2025-05-25T02:00:00Z",
    nextRun: "2025-05-26T02:00:00Z",
    triggerType: "schedule",
    steps: [
      {
        id: "step-6",
        name: "Fetch PayPal transactions",
        type: "api",
        status: "completed",
        startedAt: "2025-05-25T02:00:00Z",
        completedAt: "2025-05-25T02:01:00Z",
        output: "14 transactions fetched",
      },
      {
        id: "step-7",
        name: "Fetch Stripe transactions",
        type: "api",
        status: "completed",
        startedAt: "2025-05-25T02:01:00Z",
        completedAt: "2025-05-25T02:02:00Z",
        output: "8 transactions fetched",
      },
      {
        id: "step-8",
        name: "Reconcile balances",
        type: "compute",
        status: "completed",
        startedAt: "2025-05-25T02:02:00Z",
        completedAt: "2025-05-25T02:03:00Z",
        output: "All balances reconciled. No discrepancies.",
      },
      {
        id: "step-9",
        name: "Generate report",
        type: "report",
        status: "completed",
        startedAt: "2025-05-25T02:03:00Z",
        completedAt: "2025-05-25T02:04:00Z",
        output: "Daily report generated and stored",
      },
    ],
  },
  {
    id: "wf-3",
    name: "KEV Security Scan",
    description: "Scan all repositories against CISA KEV catalog",
    type: "security-scan",
    status: "active",
    schedule: "0 */1 * * *",
    lastRun: "2025-05-25T01:00:00Z",
    nextRun: "2025-05-25T02:00:00Z",
    triggerType: "schedule",
    steps: [
      {
        id: "step-10",
        name: "Sync KEV catalog",
        type: "sync",
        status: "completed",
        startedAt: "2025-05-25T01:00:00Z",
        completedAt: "2025-05-25T01:00:30Z",
        output: "1,464 vulnerabilities in catalog",
      },
      {
        id: "step-11",
        name: "Scan dependencies",
        type: "scan",
        status: "completed",
        startedAt: "2025-05-25T01:00:30Z",
        completedAt: "2025-05-25T01:05:00Z",
        output: "22 repos scanned",
      },
      {
        id: "step-12",
        name: "Generate compliance report",
        type: "report",
        status: "completed",
        startedAt: "2025-05-25T01:05:00Z",
        completedAt: "2025-05-25T01:06:00Z",
        output: "3 new findings, 0 critical",
      },
    ],
  },
  {
    id: "wf-4",
    name: "Asset Publishing Pipeline",
    description: "Automated asset deployment and CDN cache invalidation",
    type: "asset-publishing",
    status: "active",
    schedule: null,
    lastRun: "2025-05-24T22:00:00Z",
    nextRun: null,
    triggerType: "webhook",
    steps: [
      {
        id: "step-13",
        name: "Validate asset manifest",
        type: "validate",
        status: "completed",
        startedAt: "2025-05-24T22:00:00Z",
        completedAt: "2025-05-24T22:00:30Z",
        output: "Manifest valid",
      },
      {
        id: "step-14",
        name: "Upload to CDN",
        type: "upload",
        status: "completed",
        startedAt: "2025-05-24T22:00:30Z",
        completedAt: "2025-05-24T22:01:30Z",
        output: "42 assets uploaded",
      },
      {
        id: "step-15",
        name: "Invalidate cache",
        type: "cdn",
        status: "completed",
        startedAt: "2025-05-24T22:01:30Z",
        completedAt: "2025-05-24T22:02:00Z",
        output: "Cache invalidated globally",
      },
    ],
  },
  {
    id: "wf-5",
    name: "Notification Dispatch",
    description: "Multi-channel notifications for platform events",
    type: "notification",
    status: "active",
    schedule: null,
    lastRun: "2025-05-25T00:30:00Z",
    nextRun: null,
    triggerType: "event",
    steps: [
      {
        id: "step-16",
        name: "Process event queue",
        type: "queue",
        status: "completed",
        startedAt: "2025-05-25T00:30:00Z",
        completedAt: "2025-05-25T00:30:10Z",
        output: "5 events processed",
      },
      {
        id: "step-17",
        name: "Dispatch notifications",
        type: "notify",
        status: "completed",
        startedAt: "2025-05-25T00:30:10Z",
        completedAt: "2025-05-25T00:30:20Z",
        output: "12 notifications sent",
      },
    ],
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    timestamp: "2025-05-25T01:00:00Z",
    type: "security",
    severity: "warning",
    title: "KEV Scan: 3 New Findings",
    message:
      "WALKOFF repository has 1 critical vulnerability requiring remediation by 2025-12-19.",
    read: false,
    actionUrl: "/admin/security",
  },
  {
    id: "notif-2",
    timestamp: "2025-05-25T00:30:00Z",
    type: "deployment",
    severity: "success",
    title: "Staging Deployment Complete",
    message: "Supervisor staging environment updated to task definition v15.",
    read: false,
    actionUrl: "/admin/deployments",
  },
  {
    id: "notif-3",
    timestamp: "2025-05-24T22:00:00Z",
    type: "revenue",
    severity: "info",
    title: "Revenue: $12,500 Received",
    message: "PayPal Express Checkout payment for Platform License processed.",
    read: true,
    actionUrl: "/admin/revenue",
  },
  {
    id: "notif-4",
    timestamp: "2025-05-24T20:00:00Z",
    type: "asset",
    severity: "info",
    title: "Asset Scan Complete",
    message: "7 assets verified, all certificates valid.",
    read: true,
    actionUrl: "/admin/assets",
  },
  {
    id: "notif-5",
    timestamp: "2025-05-24T18:30:00Z",
    type: "deployment",
    severity: "success",
    title: "Production Deploy: Supervisor",
    message:
      "Blue-green deployment completed. Traffic switched to new task set.",
    read: true,
    actionUrl: "/admin/deployments",
  },
];

// ─── Audit Log ────────────────────────────────────────────────────────────────

export const AUDIT_LOG: AuditLogEntry[] = [
  {
    id: "audit-1",
    timestamp: "2025-05-25T01:00:00Z",
    userId: "user-1",
    userName: "admin",
    action: "SECURITY_SCAN_INITIATED",
    resource: "nextjs-commerce",
    details: "Automated KEV scan triggered",
    category: "security",
  },
  {
    id: "audit-2",
    timestamp: "2025-05-25T00:30:00Z",
    userId: "system",
    userName: "github-actions",
    action: "DEPLOYMENT_COMPLETED",
    resource: "Supervisor (staging)",
    details: "Task definition v15 deployed successfully",
    category: "deployment",
  },
  {
    id: "audit-3",
    timestamp: "2025-05-24T22:00:00Z",
    userId: "system",
    userName: "paypal-webhook",
    action: "PAYMENT_RECEIVED",
    resource: "Treasury",
    details: "PayPal Express Checkout — $12,500",
    category: "financial",
  },
  {
    id: "audit-4",
    timestamp: "2025-05-24T20:00:00Z",
    userId: "user-1",
    userName: "admin",
    action: "ASSET_SCAN_COMPLETED",
    resource: "All Assets",
    details: "7 assets verified",
    category: "asset",
  },
  {
    id: "audit-5",
    timestamp: "2025-05-24T18:30:00Z",
    userId: "system",
    userName: "github-actions",
    action: "DEPLOYMENT_COMPLETED",
    resource: "Supervisor (production)",
    details: "Blue-green deployment — traffic switched",
    category: "deployment",
  },
  {
    id: "audit-6",
    timestamp: "2025-05-24T17:30:00Z",
    userId: "user-1",
    userName: "admin",
    action: "FUND_ALLOCATION_APPROVED",
    resource: "Treasury",
    details: "$4,200 allocated for Infrastructure Scaling",
    category: "financial",
  },
];

// ─── Platform Overview ────────────────────────────────────────────────────────

export const PLATFORM_OVERVIEW: PlatformOverview = {
  repositories: { total: 22, active: 20, deploying: 1, error: 0 },
  deployments: { healthy: 7, degraded: 1, pending: 0 },
  revenue: { total: 14582400, monthly: 847500, pending: 125000 },
  assets: { total: 7, active: 7, pendingClaims: 3 },
  security: { vulnerabilities: 13, critical: 1, compliant: 2, scansRunning: 1 },
  automation: { activeWorkflows: 5, completedToday: 12, failedToday: 0 },
};
